export const urlConfig = {
    host: 'http://localhost:3002',
    userName: 'nodebb',
    getAllCategories: () => `${urlConfig.host}/discussion/categories`,
    getSingleCategoryDetails: (cid: number) => `discussion/categories/${cid}`,
    getAllTags: 'discussion/tags',
    createPost: 'discussion/writeApi/v2/topics',
    votePost: (pid: number) => `apis/discussion/writeApi/v2/posts/${pid}/vote`,
    replyPost: (tid: number) => `apis/discussion/writeApi/v2/topics/${tid}`,
    bookmarkPost: (pid: number) => `apis/discussion/writeApi/v2/posts/${pid}/bookmark`,
    recentPost: 'discussion/topics/recent',
    popularPost: `discussion/topics/popular`,
    unread: `discussion/topics/unread/total`,
    getTopic: `discussion/topic`,
    profile: `discussion/users/me`,
    fetchProfile: (slug: string) => `${urlConfig.host}/discussion/users/${slug}/about`,
    listUpVote: (slug: string) => `${urlConfig.host}/discussion/user/${slug}/upvoted`,
    listDownVoted: (slug: string) => `${urlConfig.host}/discussion/user/${slug}/downvoted`,
    listSaved: (slug: string) => `${urlConfig.host}/discussion/user/${slug}/bookmarks`,
    fetchNetworkProfile: `user/profileDetails/getUserRegistry`,
    userdetails: (slug: string) => `${urlConfig.host}/discussion/user/${slug}`,
    getContextBasedTopics: (slug: string) => `${urlConfig.host}/discussion/category/${slug}/1`
};
